<a href="https://colab.research.google.com/github/veldahung/huggingface_pipeline/blob/main/huggingface_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from transformers import pipeline

In [ ]:
# Sentiment analysis example
sentiment_analyzer = pipeline("sentiment-analysis")
#classifier=pipeline(task="sentiment-analysis", model="distilbert-base-uncased-finetuned-sst-2-english")

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


In [ ]:
classifier=pipeline(task="sentiment-analysis", model="distilbert-base-uncased-finetuned-sst-2-english")

In [ ]:
input_text = "I'm really enjoying Colab for exploring NLP!"

In [ ]:
# Sentiment analysis example
result = sentiment_analyzer(input_text)

classifier_result=classifier(input_text)

In [ ]:
print(result)

[{'label': 'POSITIVE', 'score': 0.9998200535774231}]


In [ ]:
print(classifier_result)

[{'label': 'POSITIVE', 'score': 0.9998200535774231}]


In [ ]:
classifier=pipeline(task="sentiment-analysis", model="siebert/sentiment-roberta-large-english")

In [ ]:
classifier_result=classifier(input_text)
print(classifier_result)

[{'label': 'POSITIVE', 'score': 0.9988937973976135}]


In [ ]:
summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

In [ ]:


text = ["Hugging Face is a company and platform specializing in natural language processing (NLP) and artificial intelligence (AI). They are renowned for their contributions to the development and distribution of state-of-the-art NLP models and tools. Hugging Face offers a comprehensive library known as 'Transformers,' which provides easy access to a wide range of pre-trained language models, facilitating the implementation of cutting-edge NLP applications. Additionally, the company promotes community collaboration by fostering an open-source environment, allowing developers and researchers to share and contribute to advancements in the field of NLP. Hugging Face has become a prominent hub for AI enthusiasts seeking powerful and efficient tools for language-related tasks."]

summarized_text = summarizer(text, min_length=5, max_length=140)[0]['summary_text']

print(summarized_text)


Hugging Face is a company and platform specializing in natural language processing (NLP) and artificial intelligence (AI) They are renowned for their contributions to the development and distribution of state-of-the-art NLP models and tools. The company promotes community collaboration by fostering an open-source environment.


### **Input:**

Hugging Face is a company and platform specializing in natural language processing (NLP) and artificial intelligence (AI). They are renowned for their contributions to the development and distribution of state-of-the-art NLP models and tools. Hugging Face offers a comprehensive library known as 'Transformers,' which provides easy access to a wide range of pre-trained language models, facilitating the implementation of cutting-edge NLP applications. Additionally, the company promotes community collaboration by fostering an open-source environment, allowing developers and researchers to share and contribute to advancements in the field of NLP. Hugging Face has become a prominent hub for AI enthusiasts seeking powerful and efficient tools for language-related tasks.

### **Output:**

Hugging Face is a company and platform specializing in natural language processing (NLP) and artificial intelligence (AI) They are renowned for their contributions to the development and distribution of state-of-the-art NLP models and tools. The company promotes community collaboration by fostering an open-source environment.

# **pipeline**

The `pipeline` function abstracts away the complexity of loading models, tokenizing input, and processing output. It automatically uses an appropriate pre-trained model based on the specified task, making it a convenient tool for users who want to quickly apply pre-trained models to specific NLP tasks without having to deal with the underlying details.

Here are some key points about pipelines:

1. **Ease of Use:** Pipelines simplify the code needed to perform common NLP tasks, reducing the amount of boilerplate code required.

2. **Automatic Model Selection:** Pipelines automatically select an appropriate pre-trained model for the specified task, so users don't need to manually choose and load models.

3. **Task Agnostic:** The same pipeline interface can be used for various NLP tasks, making it versatile.

4. **Default Settings:** Pipelines use default settings for tokenization and model configurations, making them suitable for users who prefer a quick and easy setup.

While pipelines are convenient for many use cases, users who need more control over the tokenization process or specific model configurations might prefer using the lower-level interfaces provided by the Transformers library.

In [ ]:
from collections import defaultdict, Counter
import json

from matplotlib import pyplot as plt
import numpy as np
import torch

#This function, print_encoding, takes a dictionary model_inputs and prints its contents in a structured and indented format.
def print_encoding(model_inputs, indent=4):
    indent_str = " " * indent
    print("{")
    for k, v in model_inputs.items():
        print(indent_str + k + ":") #Prints the key
        print(indent_str + indent_str + str(v)) #Prints the value
    print("}")

In [ ]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

# Initialize the tokenizer
tokenizer = AutoTokenizer.from_pretrained("siebert/sentiment-roberta-large-english")
# Initialize the model
model = AutoModelForSequenceClassification.from_pretrained("siebert/sentiment-roberta-large-english")

In [ ]:
# Input text
inputs = "I don't want to learn about Hugging Face Transformers!"

# Tokenize the input using the specified tokenizer and convert to PyTorch tensors
tokenized_inputs = tokenizer(inputs, return_tensors="pt")

# Forward pass through the model with the tokenized input
outputs = model(**tokenized_inputs)

# List of labels for classification (e.g., sentiment analysis)
labels = ['NEGATIVE', 'POSITIVE']

# Get the predicted class by selecting the index with the highest logit value
# "logits" refer to the raw, unnormalized predictions that a model generates
#Logits are the output of a neural network before it undergoes a softmax activation function.
prediction = torch.argmax(outputs.logits)


# Print the original input text
print("Input:")
print(inputs)
print()

# Print the tokenized input
print("Tokenized Inputs:")
print_encoding(tokenized_inputs)
print()

# Print the model outputs, which include logits and other information
print("Model Outputs:")
print(outputs)
print()
#The loss field is None, indicating that no loss value was computed.
#These logits are the model's unnormalized predictions for each class.
#grad_fn: This attribute indicates the gradient function that was used to compute the tensor.
#Hidden states are intermediate representations of the input sequence at different layers of the model.
#Attention weights show how much attention the model is giving to different parts of the input sequence.

# Print the final prediction
print(f"The prediction is {labels[prediction]}")

Input:
I don't want to learn about Hugging Face Transformers!

Tokenized Inputs:
{
    input_ids:
        tensor([[    0,   100,   218,    75,   236,     7,  1532,    59, 30581,  3923,
         12346, 34379,   328,     2]])
    attention_mask:
        tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
}

Model Outputs:
SequenceClassifierOutput(loss=None, logits=tensor([[ 3.9164, -3.5262]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

The prediction is NEGATIVE


Sentiment Analysis with Padding:

Imagine you have two sentences for sentiment analysis:

Sentence 1: "I had a great time at the park!" (5 words)

Sentence 2: "The movie was so disappointing." (6 words)

To process both sentences together in a batch, they need to be the same length. So, you add a padding token to Sentence 1.


If the model doesn't have an attention mask:

It analyzes all 6 tokens, including the padding in Sentence 1.

This might confuse the model and lead to inaccurate sentiment prediction.
With an attention mask:

The mask is [1, 1, 1, 1, 1, 0] for Sentence 1.

The model focuses only on the valid tokens ("I had a great time") and ignores the padding token.

This leads to a more accurate positive sentiment prediction for Sentence 1.

In [ ]:
inputs = "I'm excited to learn about Hugging Face Transformers!"
tokenized_inputs = tokenizer(inputs, return_tensors="pt")
outputs = model(**tokenized_inputs)

labels = ['NEGATIVE', 'POSITIVE']
prediction = torch.argmax(outputs.logits)


print("Input:")
print(inputs)
print()
print("Tokenized Inputs:")
print_encoding(tokenized_inputs)
print()
print("Model Outputs:")
print(outputs)
print()
print(f"The prediction is {labels[prediction]}")

Input:
I'm excited to learn about Hugging Face Transformers!

Tokenized Inputs:
{
    input_ids:
        tensor([[    0,   100,   437,  2283,     7,  1532,    59, 30581,  3923, 12346,
         34379,   328,     2]])
    attention_mask:
        tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
}

Model Outputs:
SequenceClassifierOutput(loss=None, logits=tensor([[-3.7605,  2.9262]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

The prediction is POSITIVE


可以把不同模型依自己需要串起來，例如要做一個輸入相片得出一個故事的音檔，可以將三個模型：image to text, LLM, text to speech，三個模型串起來

image to text：得出圖片的相關敘述

LLM：一照圖片的文自描述產生故事

text to speech：將得出的故事唸出來